spring.application.name=vacation-api
logging.level.root=DEBUG

server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:postgresql://localhost:5432/vacationdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true